//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBADataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int ID { get; set; }
        public string Team1 { get; set; }
        public string Team2 { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string Description { get; set; }
        public Nullable<int> ScoreTeam1 { get; set; }
        public Nullable<int> ScoreTeam2 { get; set; }
    }
}
